### ISSUE TITLE
CameraController.ApplyCameraSettings () // Java.Lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by JTOne123** [Redth/ZXing.Net.Mobile#1003]
Hello,

I don't have a lot of info about this issue, I never experience it personally, but it exists in my logs.

It looks like the issue happens sometimes on the Redmi Note 9 and Redmi Note 7 phones only.

Just placed it here for further investigation.

**Stack traces:**
```
JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Camera.GetParameters ()
CameraController.ApplyCameraSettings ()
CameraController.RefreshCamera ()
CameraAnalyzer.RefreshCamera ()
ZXingSurfaceView.SurfaceChanged (Android.Views.ISurfaceHolder holder, Android.Graphics.Format format, System.Int32 wx, System.Int32 hx)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.52(intptr,intptr)
java.lang.RuntimeException: getParameters failed (empty parameters)
android.hardware.Camera.native_getParameters(Native Method)
android.hardware.Camera.getParameters Camera.java:2223
crc6480997b3ef81bf9b2.ZXingSurfaceView.n_surfaceChanged(Native Method)
crc6480997b3ef81bf9b2.ZXingSurfaceView.surfaceChanged(Unknown Source:0)
android.view.SurfaceView.updateSurface SurfaceView.java:904
android.view.SurfaceView.setFrame SurfaceView.java:430
android.view.View.layout View.java:22155
crc643f46942d9dd1fff9.ViewRenderer_2.n_onLayout(Native Method)
crc643f46942d9dd1fff9.ViewRenderer_2.onLayout(Unknown Source:0)
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3)
crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_onLayout(Native Method)
crc643f46942d9dd1fff9.Platform_DefaultRenderer.onLayout(Unknown Source:0)
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3)
crc643f46942d9dd1fff9.PageRenderer.n_onLayout(Native Method)
crc643f46942d9dd1fff9.PageRenderer.onLayout(Unknown Source:0)
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3)
crc64720bb2db43a66fe9.NavigationPageRenderer.n_onLayout(Native Method)
crc64720bb2db43a66fe9.NavigationPageRenderer.onLayout(Unknown Source:0)
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3)
crc643f46942d9dd1fff9.PlatformRenderer.n_onLayout(Native Method)
crc643f46942d9dd1fff9.PlatformRenderer.onLayout(Unknown Source:0)
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.widget.RelativeLayout.onLayout RelativeLayout.java:1103
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.widget.LinearLayout.setChildFrame LinearLayout.java:1829
android.widget.LinearLayout.layoutVertical LinearLayout.java:1673
android.widget.LinearLayout.onLayout LinearLayout.java:1582
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
com.android.internal.policy.DecorView.onLayout DecorView.java:810
android.view.View.layout View.java:22160
android.view.ViewGroup.layout ViewGroup.java:6395
android.view.ViewRootImpl.performLayout ViewRootImpl.java:3318
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2814
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1887
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8042
android.view.Choreographer$CallbackRecord.run Choreographer.java:969
android.view.Choreographer.doCallbacks Choreographer.java:793
android.view.Choreographer.doFrame Choreographer.java:728
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:954
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:224
android.app.ActivityThread.main ActivityThread.java:7561
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:539
com.android.internal.os.ZygoteInit.main ZygoteInit.java:995
```

**Comment by Softtinn** [comment]
We are also getting this error:

Xamarin Exception Stack: Java.Lang.RuntimeException: getParameters failed (empty parameters) at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <400f0c2581b0442cbe945dcac12f80a8>:0 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <400f0c2581b0442cbe945dcac12f80a8>:0 at Android.Hardware.Camera.GetParameters () [0x0000a] in <766227aeb91f4c1083445bbd3ab18bed>:0 at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x0001d] in <415a1994d1fb4a9eb9ebd281bf696e91>:0 at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00009] in <415a1994d1fb4a9eb9ebd281bf696e91>:0 at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00000] in <415a1994d1fb4a9eb9ebd281bf696e91>:0 at ZXing.Mobile.ZXingSurfaceView.SurfaceChanged (Android.Views.ISurfaceHolder holder, Android.Graphics.Format format, System.Int32 wx, System.Int32 hx) [0x00007] in <415a1994d1fb4a9eb9ebd281bf696e91>:0 at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <4cccad0cc4a540deb37cad8c87d22b07>:0 at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <766227aeb91f4c1083445bbd3ab18bed>:0 at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <766227aeb91f4c1083445bbd3ab18bed>:0 at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <766227aeb91f4c1083445bbd3ab18bed>:0 at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.56(intptr,intptr) at java.lang.RuntimeException: getParameters failed (empty parameters) at android.hardware.Camera.native_getParameters(Native Method) at android.hardware.Camera.getParameters(Camera.java:2153) at crc6480997b3ef81bf9b2.ZXingSurfaceView.n_surfaceChanged(Native Method) at crc6480997b3ef81bf9b2.ZXingSurfaceView.surfaceChanged(Unknown Source:0) at android.view.SurfaceView.updateSurface(SurfaceView.java:1300) at android.view.SurfaceView.setFrame(SurfaceView.java:646) at android.view.View.layout(View.java:24472) at crc643f46942d9dd1fff9.ViewRenderer_2.n_onLayout(Native Method) at crc643f46942d9dd1fff9.ViewRenderer_2.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3) at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_onLayout(Native Method) at crc643f46942d9dd1fff9.Platform_DefaultRenderer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3) at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_onLayout(Native Method) at crc643f46942d9dd1fff9.Platform_DefaultRenderer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3) at crc643f46942d9dd1fff9.PageRenderer.n_onLayout(Native Method) at crc643f46942d9dd1fff9.PageRenderer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3) at crc64720bb2db43a66fe9.NavigationPageRenderer.n_onLayout(Native Method) at crc64720bb2db43a66fe9.NavigationPageRenderer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(Unknown Source:3) at crc64720bb2db43a66fe9.MasterDetailContainer.n_onLayout(Native Method) at crc64720bb2db43a66fe9.MasterDetailContainer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56) at crc64720bb2db43a66fe9.MasterDetailPageRenderer.n_onLayout(Native Method) at crc64720bb2db43a66fe9.MasterDetailPageRenderer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at crc643f46942d9dd1fff9.PlatformRenderer.n_onLayout(Native Method) at crc643f46942d9dd1fff9.PlatformRenderer.onLayout(Unknown Source:0) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673) at android.widget.LinearLayout.onLayout(LinearLayout.java:1582) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673) at android.widget.LinearLayout.onLayout(LinearLayout.java:1582) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225) at android.view.View.layout(View.java:24475) at android.view.ViewGroup.layout(ViewGroup.java:7383) at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010) at android.view.Choreographer.doCallbacks(Choreographer.java:809) at android.view.Choreographer.doFrame(Choreographer.java:744) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8587) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) Thread 2: 0 dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2) 1 java.lang.Thread.getStackTrace(Thread.java:1736) 2 java.lang.Thread.getAllStackTraces(Thread.java:1812) 3 com.microsoft.appcenter.crashes.Crashes.saveUncaughtException 4 com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException 5 mono.java.lang.RunnableImplementor.n_run 6 mono.java.lang.RunnableImplementor.run 7 android.os.Handler.handleCallback(Handler.java:938) 8 android.os.Handler.dispatchMessage(Handler.java:99) 9 android.os.Looper.loop(Looper.java:246) 10 android.app.ActivityThread.main(ActivityThread.java:8587) 11 java.lang.reflect.Method.invoke(Method.java:-2) 12 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) Thread 14597: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Object.wait(Object.java:442) 2 java.lang.Object.wait(Object.java:568) 3 java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217) 4 java.lang.Daemons$Daemon.run(Daemons.java:139) 5 java.lang.Thread.run(Thread.java:923) Thread 14598: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Object.wait(Object.java:442) 2 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190) 3 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211) 4 java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273) 5 java.lang.Daemons$Daemon.run(Daemons.java:139) 6 java.lang.Thread.run(Thread.java:923) Thread 14599: 0 java.lang.Thread.sleep(Thread.java:-2) 1 java.lang.Thread.sleep(Thread.java:442) 2 java.lang.Thread.sleep(Thread.java:358) 3 java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:390) 4 java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:419) 5 java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325) 6 java.lang.Daemons$Daemon.run(Daemons.java:139) 7 java.lang.Thread.run(Thread.java:923) Thread 14607: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:335) 2 android.os.Looper.loop(Looper.java:206) 3 android.os.HandlerThread.run(HandlerThread.java:67) Thread 14609: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:335) 2 android.os.Looper.loop(Looper.java:206) 3 android.os.HandlerThread.run(HandlerThread.java:67) Thread 14610: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:335) 2 android.os.Looper.loop(Looper.java:206) 3 android.os.HandlerThread.run(HandlerThread.java:67) Thread 14623: 0 java.lang.Object.wait(Object.java:-2) 1 com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:106) 2 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 3 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 4 java.lang.Thread.run(Thread.java:923) Thread 14625: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Object.wait(Object.java:442) 2 java.lang.Object.wait(Object.java:568) 3 com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313) 4 com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42) 5 com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288) Thread 14629: 0 sun.misc.Unsafe.park(Unsafe.java:-2) 1 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 2 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:459) 3 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362) 4 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:920) 5 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092) 6 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 7 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 8 java.lang.Thread.run(Thread.java:923)

**Comment by sdmimaye** [comment]
Same problem here:

JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Camera.GetParameters ()
CameraController.ApplyCameraSettings ()
CameraController.RefreshCamera ()
CameraAnalyzer.RefreshCamera ()
ZXingSurfaceView.SurfaceChanged (Android.Views.ISurfaceHolder holder, Android.Graphics.Format format, System.Int32 wx, System.Int32 hx)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.32(intptr,intptr)
java.lang.RuntimeException: getParameters failed (empty parameters)
android.hardware.Camera.native_getParameters(Native Method)
android.hardware.Camera.getParameters Camera.java:2138
crc6480997b3ef81bf9b2.ZXingSurfaceView.n_surfaceChanged(Native Method)
crc6480997b3ef81bf9b2.ZXingSurfaceView.surfaceChanged ZXingSurfaceView.java:92
android.view.SurfaceView.updateSurface SurfaceView.java:1165
android.view.SurfaceView.lambda$new$0$SurfaceView SurfaceView.java:173
android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
android.view.ViewTreeObserver.dispatchOnPreDraw ViewTreeObserver.java:1093
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:3094
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1948
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8177
android.view.Choreographer$CallbackRecord.run Choreographer.java:972
android.view.Choreographer.doCallbacks Choreographer.java:796
android.view.Choreographer.doFrame Choreographer.java:731
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:957
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:223
android.app.ActivityThread.main ActivityThread.java:7660
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:592
com.android.internal.os.ZygoteInit.main ZygoteInit.java:947

**Comment by AshwinKmr2502** [comment]
Any update on this issue?
