### ISSUE TITLE
RequestPermissionsAsync throws PermissionException

### ISSUE THREAD

**Issue by mmoraga** [Redth/ZXing.Net.Mobile#1053]
I've ported my Xamarin.Android app to `dotnet6.0-android` and get this exception when trying to run the `PermissionsHandler.RequestPermissionsAsync()` method. I tried wrapping the call itself in `BeginInvokeOnMainThread` but get the same result.

```
[2022-09-02T14:12:55.087Z] Fatal : 'App': Unhandled exception 'System.AggregateException: AggregateException_ctor_DefaultMessage (Permission request must be invoked on main thread.)
 ---> Xamarin.Essentials.PermissionException: Permission request must be invoked on main thread.
   at Xamarin.Essentials.Permissions.BasePlatformPermission.RequestAsync()
   at ZXing.Net.Mobile.Android.PermissionsHandler.RequestPermissionsAsync()
   Exception_EndOfInnerExceptionStack
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Result()
   at Stratus.AndroidClient.MainActivity.LaunchScannerIntent()
   at Stratus.AndroidClient.MainActivity.NativeBridge(String message)
   ```
 
I've seen there is a new ZXing.Net.Maui package, but since this is just  regular `net6.0-android` and not a maui project, I don't think it's applicable for my use case.

This is using version `3.1.0-beta2`.

**Comment by mmoraga** [comment]
I solved this by calling `Xamarin.Essentials.Permissions.RequestAsync<Permissions.Camera>()` directly instead.
