### ISSUE TITLE
IOS App crash with Null Reference Exception at SetupCaptureSession()

### ISSUE THREAD

**Issue by jamesingreersc** [Redth/ZXing.Net.Mobile#1078]
I am in the process of updating a native xamarin ios app to a Microsoft.IOS .Net 6 app. I am using the ZXing.Net6.Mobile nuget which I used to replace the older ZXing.Net.Mobile .

The code being used was seamless as far as building but I am getting a null reference exception when calling the .Scan method. It's crashing all the way back to the Main application file. Just before the crash the camera does try to open.

This is the stack trace I am getting
object reference not set to instance of an object
   at ZXing.Mobile.ZXingScannerView.SetupCaptureSession()
   at ZXing.Mobile.ZXingScannerView.<StartScanning>b__42_0()
   at Foundation.NSActionDispatcher.Apply()
   at Foundation.NSObject.InvokeOnMainThread(Action )
   at ZXing.Mobile.ZXingScannerView.StartScanning(Action`1 scanResultHandler, MobileBarcodeScanningOptions options)
   at ZXing.Mobile.ZXingScannerViewController.<ViewDidAppear>b__33_1()
   at Foundation.NSAsyncActionDispatcher.Apply()
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at DSDRouteManager.iOS.Application.Main(String[] args) in /Users/jamespridgen/Desktop/DSDRouteManager/DSDRouteManager.IOS/Main.cs:line
   
  These are the keys I have in Info.plist
  	<key>NSCameraUsageDescription</key>
	<string>Can we use your camera</string>
       <key>Privacy - Camera Usage Description</key>
	<string>Taking picture barcode</string>
	<key>Privacy - Photo Library Usage Description</key>
	<string>Taking picture barcode</string>	
	
This is the code I am using to call the camera

              var auth = AVCaptureDevice.GetAuthorizationStatus(AVAuthorizationMediaType.Video);
              if (auth == AVAuthorizationStatus.NotDetermined)
              {
                  if (AVCaptureDevice.RequestAccessForMediaTypeAsync(AVAuthorizationMediaType.Video).Result)
                  {
                      auth = AVCaptureDevice.GetAuthorizationStatus(AVAuthorizationMediaType.Video);
                  }
              }

           // camera access has been granted at this point
              var cameraScanner = new MobileBarcodeScanner(this); // "this" is the UIViewController
              var options = Util.GetMobileBarcodeScanningOptions();
              var result = await cameraScanner.Scan(options,true); // crash happens here

              
              Scanning options
              
     return new MobileBarcodeScanningOptions()
       {
           AutoRotate = true,
           PossibleFormats = new List<BarcodeFormat>()
           {
               BarcodeFormat.All_1D,
               BarcodeFormat.QR_CODE,
               BarcodeFormat.CODE_39,
               BarcodeFormat.CODE_128,
               BarcodeFormat.UPC_A,
               BarcodeFormat.UPC_E
           }
       };
       
       Do I need some kind of initialization that the older nuget didn't require.
       
       Any help would be much appreciated
       James

**Comment by spinspin** [comment]
@jamesingreersc  Did you find a solution to this?  I'm running into the same issue .

**Comment by jamesingreersc** [comment]
@spinspin No, I found nothing helpful. I can see that the UINavigationController is null when the scanner is being initialized. I'm not sure if this a bug in .Net or not. I am going to test the old version of the app that does work and see if it's null there or not.

**Comment by spinspin** [comment]
It's probably a bug. I've just written some native net7.0-ios code which handles barcode scanning so I don't need to use this library  let me know if you want it.

**Comment by jamesingreersc** [comment]
@spinspin That would be awesome if I could use your code. Thanks bunches!!

**Comment by spinspin** [comment]
@jamesingreersc  this should be enough to get going , I'm using MvvmCross but the core functionality to create a  barcode scanner is in here  

public class BarcodeScannerViewController : MvxViewController<BarcodeScannerViewModel>
    {
        AVCaptureSession captureSession;
        AVCaptureVideoPreviewLayer previewLayer;
        public Action<string> BarcodeScanned { get; set; }

        public BarcodeScannerViewController(IntPtr handle) : base(handle) { }

        public BarcodeScannerViewController(){}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            SetUI();
            StartScanning();
        }

        private void SetUI()
        {        
            View.BackgroundColor = UIColor.White;

            NavigationController.NavigationBar.TitleTextAttributes = new UIStringAttributes
            {
                Font = UIFont.FromName("Gill Sans", 20),
                ForegroundColor = UIColor.Black
            };

            NavigationItem.BackButtonTitle = "";
            NavigationItem.Title = "Barcode Scanning";

            var closeImage = UIImage.FromBundle("Close36pt").ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);

            if (DeviceInfo.Version.Major >= 13)
            {
                closeImage.ApplyTintColor(UIColor.Black);
            }

            var closeButton = new UIButton();
            closeButton.SetImage(closeImage, UIControlState.Normal);
            closeButton.TintColor = UIColor.Black;
            NavigationItem.SetRightBarButtonItem(new UIBarButtonItem(closeButton),true);

            closeButton.TouchUpInside += (sender, args) =>
            {
                ViewModel.OnBarcodeScanCancel();
            };
        }

    
        void StartScanning()
        {
            try
            {
                captureSession = new AVCaptureSession();
                var videoCaptureDevice = AVCaptureDevice.GetDefaultDevice(AVMediaTypes.Video);
                // Create an input from the video capture device
                var videoInput = AVCaptureDeviceInput.FromDevice(videoCaptureDevice, out NSError error);

                if (error != null)
                {
                    ViewModel.OnBarcodeScanError();
                    return;
                }
                else
                {
                    captureSession.AddInput(videoInput);
                }

                // Create a metadata output and set its delegate
                var metadataOutput = new AVCaptureMetadataOutput
                {
                    RectOfInterest = UIScreen.MainScreen.Bounds
                };

                metadataOutput.SetDelegate(new OutputDelegate(DidScanBarcode), DispatchQueue.MainQueue);
                captureSession.AddOutput(metadataOutput);
                metadataOutput.MetadataObjectTypes = AVMetadataObjectType.EAN13Code
                                       | AVMetadataObjectType.QRCode
                                       | AVMetadataObjectType.EAN8Code
                                       | AVMetadataObjectType.Code128Code;

                // Create a preview layer to show the view from the camera
                previewLayer = new AVCaptureVideoPreviewLayer(captureSession)
                {
                    Frame = new CGRect(View.Bounds.X, View.Bounds.Y +50 , View.Bounds.Width, View.Bounds.Height-50)
                };


                View.Layer.AddSublayer(previewLayer);

                // Create a new UIView with the desired dimensions.
                var redLineView = new UIView
                {
                    BackgroundColor = UIColor.Red,
                    Frame = new CGRect(0, previewLayer.Frame.GetMidY(), View.Bounds.Width, 2) // This line is 2 points thick and centered in the preview layer.
                };

                // Add the view to the parent view.
                View.AddSubview(redLineView);

                // Start the capture session
                captureSession.StartRunning();
            }

            catch (Exception)
            {
                ViewModel.OnBarcodeScanError();
            }
        }

        private void DidScanBarcode(string barcode)
        {
            // Stop the capture session and notify the delegate
            captureSession.StopRunning();
            captureSession.Dispose(); // release the capture session
            captureSession = null; // set it to null

            // Remove the preview layer
            previewLayer.RemoveFromSuperLayer();
            previewLayer.Dispose(); // Dispose the preview layer
            previewLayer = null; // set it to null

            ViewModel.OnBarcodeScanSuccess(barcode);
        }


        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);

            if (IsBeingDismissed || IsMovingFromParentViewController)
            {
                Cleanup();
            }
        }

        void Cleanup()
        {
            // Stop the capture session and release resources
            captureSession.StopRunning();
            captureSession.Dispose();
            captureSession = null;

            previewLayer.RemoveFromSuperLayer();
            previewLayer.Dispose();
            previewLayer = null;
        }
    }

    class OutputDelegate : AVCaptureMetadataOutputObjectsDelegate
    {
        Action<string> barcodeHandler;

        public OutputDelegate(Action<string> barcodeHandler)
        {
            this.barcodeHandler = barcodeHandler;
        }

        public override void DidOutputMetadataObjects(AVCaptureMetadataOutput captureOutput, AVMetadataObject[] metadataObjects, AVCaptureConnection connection)
        {
            if (metadataObjects != null && metadataObjects.Length > 0)
            {
                var readableObject = metadataObjects[0] as AVMetadataMachineReadableCodeObject;

                if (readableObject != null)
                {
                    var barcode = readableObject.StringValue;
                    barcodeHandler?.Invoke(barcode);
                }
            }
        }
    }

    public interface IBarcodeScanningServiceDelegate
    {
        void DidFinishScanning(string barcode);
    }

**Comment by jamesingreersc** [comment]
@spinspin Thanks for this. It helped a bunch!
