### ISSUE TITLE
Camera just has a black screen 

### ISSUE THREAD

**Issue by jjohnnyl** [Redth/ZXing.Net.Mobile#212]
Camera just giving me a black screen on my Nexus 6p, anyone else have the same issue?

I've given the Android app camera permission and it's always worked in the past my Sony Z2.

**Comment by jjohnnydotnet** [comment]
Got Camera Exclusive access
[ZXing.Net.Mobile] Checking Number of cameras...
[ZXing.Net.Mobile] Found 2 cameras...
[ZXing.Net.Mobile] Found Back Camera, opening...
[CameraBase] An error occurred while connecting to camera: 0
Releasing Exclusive access to camera
Setup Error: Java.Lang.RuntimeException: Fail to connect to camera service
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00064] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1301 
  at Android.Hardware.Camera.Open (Int32 cameraId) [0x00044] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Hardware.Camera.cs:4947 
  at ZXing.Mobile.ZXingSurfaceView.StartScanning (ZXing.Mobile.MobileBarcodeScanningOptions options, System.Action`1 callback) [0x0011a] in <filename unknown>:0 
  --- End of managed exception stack trace ---
java.lang.RuntimeException: Fail to connect to camera service
	at android.hardware.Camera.<init>(Camera.java:495)
	at android.hardware.Camera.open(Camera.java:341)
	at md5fbe1730f19340e19ad8e4d756e4d2723.ZXingScannerFragment.n_onResume(Native Method)
	at md5fbe1730f19340e19ad8e4d756e4d2723.ZXingScannerFragment.onResume(ZXingScannerFragment.java:38)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2005)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2011)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:187)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:426)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:415)
	at android.app.Activity.performResume(Activity.java:6351)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
SurfaceCreated took 67.1202ms
[OpenGLRenderer] endAllStagingAnimators on 0x7f717e2c00 (RippleDrawable) with handle 0x7f71784460
Thread finished: <Thread Pool> #13
Thread started: <Thread Pool> #14

**Comment by jjohnnydotnet** [comment]
Found the issue, was an issue with Marshmallow not activating the camera.

No wonder it was working on my old phone and not my new Nexus 6p :)

**Comment by Redth** [comment]
Thanks. This will be working properly on marshmallow in the next release
