### ISSUE TITLE
Exception when rotating: The stream number provided was invalid

### ISSUE THREAD

**Issue by bruzkovsky** [Redth/ZXing.Net.Mobile#250]
The exception seems to occur when rotating the Device. Occurred on Win10 Mobile on a Lumia 550.

Message:

The stream number provided was invalid.
PreviewState

at Windows.Media.Capture.MediaCapture.SetEncodingPropertiesAsync(MediaStreamType mediaStreamType, IMediaEncodingProperties mediaEncodingProperties, MediaPropertySet encoderProperties)
at ZXing.Mobile.ZXingScannerControl.<SetPreviewRotationAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ZXing.Mobile.ZXingScannerControl.<displayInformation_OrientationChanged>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()"

**Comment by bruzkovsky** [comment]
https://github.com/Redth/ZXing.Net.Mobile/blob/f7ca5e6876850077ce73d2ae23cc7869cc0efa7a/Source/ZXing.Net.Mobile.WindowsUniversal/ZXingScannerControl.xaml.cs#L36

There seems to be the error. After subscribing the OrientationChanged event you never unsubscribe it. I have commented it out in my local clone for now. Maybe the event can be subscribed and unsubscribed in the Loaded/Unloaded handlers of the Control?

**Comment by Redth** [comment]
The event unsubscribe is now fixed in master, thanks!
