### ISSUE TITLE
Null reference resuming app with Scanner Activity already running.

### ISSUE THREAD

**Issue by Jtdawgzone** [Redth/ZXing.Net.Mobile#274]
**Using ZXing.Net.Mobile.2.0.4.46 with a custom view.**

**Steps to Repo:**

**1.) Have a main activity start Zxing with a button press.**
**2.) Pass Zxing a custom view**
**3.) While the Scanner is open background the app**
**4.) Resume and observe crash from Fragment not checking if view is null**

**On Android 5.1** Java.Lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup.
Java.Lang.IllegalArgumentExceptionCannot add a null child view to a ViewGroup
Raw
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xa0cd2f48 + 0x00024> in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) <0xae6fe3f8 + 0x000bf> in <filename unknown>:0 
  at Android.Views.ViewGroup.AddView (Android.Views.View child, Android.Views.LayoutParams params) <0x9e604700 + 0x001c3> in <filename unknown>:0 
  at ZXing.Mobile.ZXingScannerFragment.OnStart () <0x9e604d88 + 0x0007b> in <filename unknown>:0 
  at Android.Support.V4.App.Fragment.n_OnStart (IntPtr jnienv, IntPtr native__this) <0x9e604d38 + 0x00037> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:44624fcb-742e-456b-bfd2-8b4942b19771 (intptr,intptr)
  --- End of managed exception stack trace ---
java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.view.ViewGroup.addView(ViewGroup.java:4119)
	at android.view.ViewGroup.addView(ViewGroup.java:4099)
	at md59d50db212e0bbf7132bbad8b3d837d51.ZXingScannerFragment.n_onStart(Native Method)
	at md59d50db212e0bbf7132bbad8b3d837d51.ZXingScannerFragment.onStart(ZXingScannerFragment.java:38)
	at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2006)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:176)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:517)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
	at android.app.Activity.performStart(Activity.java:6613)
	at android.app.Activity.performRestart(Activity.java:6683)
	at android.app.Activity.performResume(Activity.java:6688)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4102)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**On Android 4.0.4:**
Java.Lang.RuntimeException: java.lang.reflect caused an unexpected termination
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x56104990 + 0x00024> in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) <0x55326818 + 0x000bf> in <filename unknown>:0 
  at Android.Views.ViewGroup.AddView (Android.Views.View child, Android.Views.LayoutParams params) <0x56003a88 + 0x001c3> in <filename unknown>:0 
  at ZXing.Mobile.ZXingScannerFragment.OnStart () <0x56004100 + 0x0007b> in <filename unknown>:0 
  at Android.Support.V4.App.Fragment.n_OnStart (IntPtr jnienv, IntPtr native__this) <0x560040b0 + 0x00037> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:c16226b4-f578-4015-a5c4-b89edcce8132 (intptr,intptr)
  --- End of managed exception stack trace ---
java.lang.NullPointerException
	at android.view.ViewGroup.addViewInner(ViewGroup.java:3653)
	at android.view.ViewGroup.addView(ViewGroup.java:3525)
	at android.view.ViewGroup.addView(ViewGroup.java:3505)
	at md59d50db212e0bbf7132bbad8b3d837d51.ZXingScannerFragment.n_onStart(Native Method)
	at md59d50db212e0bbf7132bbad8b3d837d51.ZXingScannerFragment.onStart(ZXingScannerFragment.java:38)
	at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2006)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:176)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:517)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1195)
	at android.app.Activity.performStart(Activity.java:4553)
	at android.app.Activity.performRestart(Activity.java:4604)
	at android.app.Activity.performResume(Activity.java:4617)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2849)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2904)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:5060)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Jtdawgzone** [comment]
Forking from your repo it looks like you may have solved this literally yesterday. If that's true, when do you plan to release the new version?

**Comment by Redth** [comment]
I believe PR #302 should fix this
