### ISSUE TITLE
Android support for >= 2.3 and < 4.0.3

### ISSUE THREAD

**Issue by daniherculano84** [Redth/ZXing.Net.Mobile#276]
Since I updated to last ZXing versions, I am getting this error when trying to open scanner with Galaxy Ace 2 GT-I8160 (API 10). I don't know why other devices are working normally. The exception is:

```
System.TypeInitializationException: The type initializer for 'ZXing.Mobile.MobileBarcodeScanner' threw an exception. ---> Java.Lang.ClassNotFoundException: md59d50db212e0bbf7132bbad8b3d837d51.ActivityLifecycleContextListener in loader dalvik.system.PathClassLoader[/data/app/sgdmobile.md-1.apk]
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0
  at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00064] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:195
  at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue[] parms) [0x0001d] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:203
  at Android.Runtime.JNIEnv.FindClass (System.String classname) [0x00007] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:494
  at Android.Runtime.JNIEnv.FindClass (System.Type type) [0x00009] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:434
  at --- End of managed exception stack trace ---
  at java.lang.ClassNotFoundException: md59d50db212e0bbf7132bbad8b3d837d51.ActivityLifecycleContextListener in loader dalvik.system.PathClassLoader[/data/app/sgdmobile.md-1.apk]
  at at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
  at at mono.android.preference.Preference_OnPreferenceClickListenerImplementor.n_onPreferenceClick(Native Method)
  at at mono.android.preference.Preference_OnPreferenceClickListenerImplementor.onPreferenceClick(Preference_OnPreferenceClickListenerImplementor.java:29)
  at at android.preference.Preference.performClick(Preference.java:812)
  at at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:190)
  at at android.widget.AdapterView.performItemClick(AdapterView.java:284)
  at at android.widget.ListView.performItemClick(ListView.java:3740)
  at at android.widget.AbsListView$PerformClick.run(AbsListView.java:2000)
  at at android.os.Handler.handleCallback(Handler.java:587)
  at at android.os.Handler.dispatchMessage(Handler.java:92)
  at at android.os.Looper.loop(Looper.java:130)
  at at android.app.ActivityThread.main(ActivityThread.java:3691)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:507)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
  at at dalvik.system.NativeStart.main(Native Method)
  --- End of inner exception stack trace ---
  at SGDMobile.MD.PreferencesSGD+<leerQR_PreferenceClick>d__1a.MoveNext () [0x00021] in d:\Desarrollo\Mono\SGDMobile\SGDMobile.MD\PreferencesSGD.cs:413
  at --- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <filename unknown>:0
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:71
  at at (wrapper dynamic-method) System.Object:9ff0e2bb-f7c4-48b5-bcfd-78b30e1d0857 (intptr,intptr)

```

And the line that throws the exception is the first on we initialize Scanner or call constructor :

```
//both lines throw exception separatelly
MobileBarcodeScanner.Initialize(Application);
MobileBarcodeScanner scanner = new MobileBarcodeScanner();
```

I must say that the problem occurs not only with my application but also the library sample for Android.

Waiting your news. Thanks.

**Comment by Redth** [comment]
Ahh so technically only android 4.0.3 and higher are supported.

I'll have a look and see if it's possible to keep down to API level 9, as I know there's some code that already works that way.
