### ISSUE TITLE
Can't get ZXing working on UWP device

### ISSUE THREAD

**Issue by wegascee** [Redth/ZXing.Net.Mobile#475]
Attached you will find a sample project, where I try to start the scanner on a Microsoft Lumia 650 with Windows 10 Mobile (10.0.14393.321). If I start the scanner I can only see a white content with gray borders and the red line in the middle like in the simulator. No scanning is possible. Am I missing a permission? I used the [init code as required](https://components.xamarin.com/gettingstarted/zxing.net.mobile.forms) for UWP in MainPage.xaml.cs after `this.InitializeComponent();`

If I press the torch, the app crashes with

> This object needs to be initialized before the requested operation can be carried out.

StackTrace:

```
   at Windows.Media.Capture.MediaCapture.get_VideoDeviceController()
   at ZXing.Mobile.ZXingScannerControl.get_HasTorch()
   at ZXing.Mobile.ZXingScannerControl.Torch(Boolean on)
   at ZXing.Net.Mobile.Forms.WindowsUniversal.ZXingScannerViewRenderer.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at ZXing.Net.Mobile.Forms.ZXingScannerPage.<.ctor>b__2_1(Button sender, EventArgs e)
   at ZXing.Net.Mobile.Forms.ZXingDefaultOverlay.<.ctor>b__7_0(Object sender, EventArgs e)
   at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked()
   at Xamarin.Forms.Platform.UWP.ButtonRenderer.OnButtonClick(Object sender, RoutedEventArgs e)
```

I tried to get the samples running, but he complained about missing NuGet packages all the time ...

What am I doing wrong?

[TestZxingUWP.zip](https://github.com/Redth/ZXing.Net.Mobile/files/613514/TestZxingUWP.zip)

**Comment by wegascee** [comment]
OK you have to add the following capabilities: Webcam & Microphone
