### ISSUE TITLE
FastAndroidCamera missing from 2.2.0

### ISSUE THREAD

**Issue by alberk8** [Redth/ZXing.Net.Mobile#527]
Hi,

I have installed the latest 2.2.0 for ZXing.Net.Mobile for Android and when I compile my program and following error crops up.  It seems that it is missing the FastAndroidCamera assembly.  Thanks.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'FastAndroidCamera, Version=2.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'FastAndroidCamera.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	CamTest	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1399	
```

**Comment by neoncube2** [comment]
I just encountered the same issue.

Adding the FastAndroidCamera package via NuGet seems to have fixed the issue for me, but it would still good to have this listed as a dependency in ZXing's Android NuGet package, of course :)

**Comment by fredrikhaglund** [comment]
I can also reproduce this issue. Changing back to 2.1.47 from 2.2.0 and the solution compiles again.

**Comment by F1nZeR** [comment]
Check latest version, it should be fixed now.

**Comment by alberk8** [comment]
It is fixed now.  Thanks.
