### ISSUE TITLE
NullReferenceException on Android

### ISSUE THREAD

**Issue by JKorsten** [Redth/ZXing.Net.Mobile#623]
Hey, 
When scanning some barcodes it sometimes works, but after a while (no reall reproductionscenario yet) it crashes and gives a NullReferenceException.

```
E/DHL.GCA.Droid.Setup(18859): System.NullReferenceException: Object reference not set to an instance of an object
E/DHL.GCA.Droid.Setup(18859):   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <7c7c485bd9034360a95deed1c4c824b8>:0 
E/DHL.GCA.Droid.Setup(18859):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <7c7c485bd9034360a95deed1c4c824b8>:0 
E/DHL.GCA.Droid.Setup(18859):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <7c7c485bd9034360a95deed1c4c824b8>:0 
E/DHL.GCA.Droid.Setup(18859):   at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <7c7c485bd9034360a95deed1c4c824b8>:0 
E/DHL.GCA.Droid.Setup(18859): --- End of stack trace from previous location where exception was thrown ---
E/DHL.GCA.Droid.Setup(18859):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
E/DHL.GCA.Droid.Setup(18859):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
E/DHL.GCA.Droid.Setup(18859):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
E/DHL.GCA.Droid.Setup(18859):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
E/DHL.GCA.Droid.Setup(18859):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
E/DHL.GCA.Droid.Setup(18859):   at (wrapper dynamic-method) System.Object:71f33231-71e9-4abc-a4e7-a73c907f8710 (intptr,intptr)
```
```
I/MonoDroid(18859): System.NullReferenceException: Object reference not set to an instance of an object
I/MonoDroid(18859):   at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <7c7c485bd9034360a95deed1c4c824b8>:0 
I/MonoDroid(18859):   at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <7c7c485bd9034360a95deed1c4c824b8>:0 
I/MonoDroid(18859):   at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <7c7c485bd9034360a95deed1c4c824b8>:0 
I/MonoDroid(18859):   at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__4.MoveNext () [0x00073] in <7c7c485bd9034360a95deed1c4c824b8>:0 
I/MonoDroid(18859): --- End of stack trace from previous location where exception was thrown ---
I/MonoDroid(18859):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
I/MonoDroid(18859):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
I/MonoDroid(18859):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
I/MonoDroid(18859):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
I/MonoDroid(18859):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
I/MonoDroid(18859):   at (wrapper dynamic-method) System.Object:71f33231-71e9-4abc-a4e7-a73c907f8710 (intptr,intptr)
```

I also see I got an RuntimeException in my logcat:
```
E/ZXING   (18859): Setup Error: Java.Lang.RuntimeException: Fail to connect to camera service
E/ZXING   (18859):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
E/ZXING   (18859):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in <a043032cf94a485190047a14918b9f60>:0 
E/ZXING   (18859):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00019] in <a043032cf94a485190047a14918b9f60>:0 
E/ZXING   (18859):   at Android.Hardware.Camera.Open (System.Int32 cameraId) [0x00021] in <cb838ba5c6ed4f90bc34911f86b1bd92>:0 
E/ZXING   (18859):   at ZXing.Mobile.CameraAccess.CameraController.OpenCamera () [0x000d1] in <7c7c485bd9034360a95deed1c4c824b8>:0 
E/ZXING   (18859):   --- End of managed Java.Lang.RuntimeException stack trace ---
E/ZXING   (18859): java.lang.RuntimeException: Fail to connect to camera service
E/ZXING   (18859): 	at android.hardware.Camera.native_setup(Native Method)
E/ZXING   (18859): 	at android.hardware.Camera.<init>(Camera.java:419)
E/ZXING   (18859): 	at android.hardware.Camera.open(Camera.java:371)
E/ZXING   (18859): 	at md5e2ed3c6b13fcfff19371c0219cb2ee1f.ZXingSurfaceView.n_surfaceCreated(Native Method)
E/ZXING   (18859): 	at md5e2ed3c6b13fcfff19371c0219cb2ee1f.ZXingSurfaceView.surfaceCreated(ZXingSurfaceView.java:65)
E/ZXING   (18859): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:602)
E/ZXING   (18859): 	at android.view.SurfaceView.access$000(SurfaceView.java:94)
E/ZXING   (18859): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:183)
E/ZXING   (18859): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:891)
E/ZXING   (18859): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
E/ZXING   (18859): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
E/ZXING   (18859): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6635)
E/ZXING   (18859): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
E/ZXING   (18859): 	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
E/ZXING   (18859): 	at android.view.Choreographer.doFrame(Choreographer.java:583)
E/ZXING   (18859): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
E/ZXING   (18859): 	at android.os.Handler.handleCallback(Handler.java:733)
E/ZXING   (18859): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/ZXING   (18859): 	at android.os.Looper.loop(Looper.java:146)
E/ZXING   (18859): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
E/ZXING   (18859): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ZXING   (18859): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/ZXING   (18859): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/ZXING   (18859): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/ZXING   (18859): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by JKorsten** [comment]
Same as #620

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
