### ISSUE TITLE
getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by THplusplus** [Redth/ZXing.Net.Mobile#686]
Some of my users are facing a crash on Android on a specific device (LeCo LEX720)
The app is based on Xamarin.Forms.
From what information I can gather, the crash happens while trying to scan a QR Code with following code:

```
IMobileBarcodeScanner scanner = new MobileBarcodeScanner();
scanner.TopText = title;
scanner.FlashButtonText = "Licht";

Result result;

try
{
	result = await scanner.Scan(new MobileBarcodeScanningOptions
	{
		PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE },
	});
}
finally
{
	// ...
}
```

Here's the HockeyApp crash report:

```
Package: <..>
Version Code: 9
Version Name: 1.0.1
Android: 7.1.2
Android Build: LePro3-userdebug 7.1.2 NJH47F 03e1b46689
Manufacturer: LeEco
Model: LEX720
Thread: main-1
CrashReporter Key: 47b4da22-ac48-4411-b331-024894fd8d49
Start Date: 2018-03-05T10:44:50.218Z
Date: 2018-03-05T10:45:11.314Z
Format: Xamarin

java.lang.RuntimeException: getParameters failed (empty parameters)
	at android.hardware.Camera.native_getParameters(Native Method)
	at android.hardware.Camera.getParameters(Camera.java:2027)
	at md5bbb8e5d2928631fa7276827c449c8050.ZXingSurfaceView.n_surfaceChanged(Native Method)
	at md5bbb8e5d2928631fa7276827c449c8050.ZXingSurfaceView.surfaceChanged(ZXingSurfaceView.java:75)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Xamarin caused by: Java.Lang.RuntimeException: getParameters failed (empty parameters)
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <97a165003f024769ae3a14b63eb60fd8>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <e781d914e19d400795568830ffe6c1a8>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <e781d914e19d400795568830ffe6c1a8>:0 
  at Android.Hardware.Camera.GetParameters () [0x0000a] in <700fd9bcdd254571b8e3b1dbe12d204f>:0 
  at ZXing.Mobile.CameraAccess.CameraController.ApplyCameraSettings () [0x00007] in <57b37b10a314448c8d6b2b9155539100>:0 
  at ZXing.Mobile.CameraAccess.CameraController.RefreshCamera () [0x00010] in <57b37b10a314448c8d6b2b9155539100>:0 
  at ZXing.Mobile.CameraAccess.CameraAnalyzer.RefreshCamera () [0x00001] in <57b37b10a314448c8d6b2b9155539100>:0 
  at ZXing.Mobile.ZXingSurfaceView+<SurfaceChanged>d__5.MoveNext () [0x0006b] in <57b37b10a314448c8d6b2b9155539100>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <97a165003f024769ae3a14b63eb60fd8>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <97a165003f024769ae3a14b63eb60fd8>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <700fd9bcdd254571b8e3b1dbe12d204f>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <700fd9bcdd254571b8e3b1dbe12d204f>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <700fd9bcdd254571b8e3b1dbe12d204f>:0 
  at (wrapper dynamic-method) System.Object:6b29c3cc-1a76-4fbe-9bdf-da86b02abad1 (intptr,intptr)
  --- End of managed Java.Lang.RuntimeException stack trace ---
```

**Comment by bensafeag** [comment]
I am having the same line `Java.Lang.RuntimeException: getParameters failed (empty parameters)` thrown. In my case, it happens after a successful scan.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
