### ISSUE TITLE
Error when app is reloaded after been tombstoned on Android.

### ISSUE THREAD

**Issue by SSElliott** [Redth/ZXing.Net.Mobile#793]
Whilst getting an Android App ready for the Good App store, I tested it with the "Do Not Keep Activities" and "No Background Process" options. 

I found when I tomb stoned the app (clicking on the square icon) and went back in, whilst the camera was scanning for a barcode in the application, it would error with a null reference exception. 

12-31 14:04:57.045	LGE Nexus 5X	Error	17134	AndroidRuntime	android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at ZXing.Mobile.ZxingActivity.OnCreate (Android.OS.Bundle bundle) [0x00038] in <819b29aa6d91462699e19a679be55a44>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <a10f61e70eeb434e952fef884856c199>:0 
  at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)
	at md5bb098716dd46c8e113564e6b42b7cde9.ZxingActivity.n_onCreate(Native Method)
	at md5bb098716dd46c8e113564e6b42b7cde9.ZxingActivity.onCreate(ZxingActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  Force finishing activity App1.App1/md5bb098716dd46c8e113564e6b42b7cde9.ZxingActivity

This happens in any simple sample project with the latest version, using the following code on a button click.
   
            MobileBarcodeScanner.Initialize(Application);
            var scanner = new ZXing.Mobile.MobileBarcodeScanner();
            scanner.AutoFocus();
            var result = await scanner.Scan();

            if (result != null)
                Console.WriteLine("Scanned Barcode: " + result.Text);

As I have no access to the zxing activity that is produced I cannot detect if it has been paused to stop scanning, so is there another work around?

Kind Regards

Steven Elliott

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Comment by SSELLIOTTHOME** [comment]
Thank you for the update, I look forward to trying out the new version.
