### ISSUE TITLE
Camera releasing slowly.

### ISSUE THREAD

**Issue by DanielMcMahon** [Redth/ZXing.Net.Mobile#896]
Hi, i was wondering if you can help me?

I have an app that heavily relies on your library. 
This would be for xamarin forms. The platform im having issues on is android 8. 

If i initiate the qr scanner and get the result from the completed scan, and immediatly after this open a camera view, the hardware on the device says that there is no camera attached when our implemenation opens. However if i wait before opening our implementation then there is no error. 

Have you ever encountered this ? Is there anything i can call or implement to make the camera release faster?

Thanks

**Comment by DanielMcMahon** [comment]
I get this stack trace when i invoke the camera straight after scanning a qr code.


```
Java.Lang.RuntimeException: No camera available.
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00068] in <26521a5118b44c858c385715922b9d5d>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x0000e] in <4ccdb3137d974856b786e1aeebbfbab6>:0 
  at Com.Google.Android.Cameraview.CameraView.Start () [0x00043] in <36b8243d010b4dd7a4067ffaf57b7a25>:0 
  at appl.Droid.Renderers.CameraViewRenderer.StartAsync (System.Threading.Tasks.TaskCompletionSource`1[TResult] completion) [0x00085] in C:\app\app\app\app.Android\Renderers\CameraViewRenderer.cs:327 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: No camera available.
	at com.google.android.cameraview.Camera2.chooseCameraIdByFacing(Camera2.java:361)
	at com.google.android.cameraview.Camera2.start(Camera2.java:213)
	at com.google.android.cameraview.CameraView.start(CameraView.java:246)
	at crc64720bb2db43a66fe9.FragmentContainer.n_onCreateView(Native Method)
	at crc64720bb2db43a66fe9.FragmentContainer.onCreateView(FragmentContainer.java:33)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by thhowl** [comment]
When I had that issues, I found that I was not properly destroying the view (or the ViewModel which the view has a reference to), and therefore not properly releasing the camera.  It works after a wait period because of garbage collection - I think - but, either way, I solved it by properly closing down my view and NOT having a my viewmodel stay in memory as a Singleton.

**Comment by knocte** [comment]
> The platform im having issues on is android 8.

@DanielMcMahon what version of ZXing.Net.Mobile were you using?

**Comment by DanielMcMahon** [comment]
No longer relevant to me as i have left the job this was related to.

**Comment by knocte** [comment]
But other people may be affected by this bug, please reopen it because no one solved it.
