### ISSUE TITLE
System.IO.FileNotFoundException: Could not load assembly 'zxing.portable, Version=0.16.2.0, Culture=neutral, PublicKeyToken=830ae994e36ac27d'.

### ISSUE THREAD

**Issue by Jakar510** [Redth/ZXing.Net.Mobile#916]
On Release builds for Zxing.Net.Mobile / Zxing.Net.Mobile.Forms (Version 3.0.0-beta5) I receive the following exception: 

	System.IO.FileNotFoundException: Could not load assembly 'zxing.portable, Version=0.16.2.0, Culture=neutral, PublicKeyToken=830ae994e36ac27d'. Perhaps it doesn't exist in the Mono for Android profile?
	File name: 'zxing.portable.dll'
	   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/azdo/_work/204/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 241
	   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference) in /Users/builder/azdo/_work/204/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 191
	   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/MetadataResolver.cs:line 110
	   at Mono.Cecil.TypeReference.Resolve() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/TypeReference.cs:line 276
	   at Mono.Linker.TypeReferenceExtensions.<GetMethods>d__4.MoveNext()
	   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodReference method)
	   at Mono.Linker.Steps.TypeMapStep.<GetBaseMethodsInInterfaceHierarchy>d__16.MoveNext()
	   at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod(MethodDefinition method)
	   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
	   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
	   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
	   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
	   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
	   at Mono.Linker.Pipeline.Process(LinkContext context)
	   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
	   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
	   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
	   at Xamarin.Android.Tasks.AndroidTask.Execute()

**Comment by Jakar510** [comment]
Deleting the obj and bin folders fixed it. Don't know if it's a visual studio issue or not.

**Comment by danielcuzzolin** [comment]
I have the same issue, after deleting the obj and bin folders the problem persist. The problem occurs only in Release mode, in Debug mode it works fine.
Any idea how to resolve?

**Comment by danielcuzzolin** [comment]
I'm using Visual Studio 2019 for MAC 8.7.4..

**Comment by knocte** [comment]
> I updated Visual studio to the new preview version and now it works.

What's the version of that preview?

**Comment by danielcuzzolin** [comment]
> > I updated Visual studio to the new preview version and now it works.
> 
> What's the version of that preview?

8.8

**Comment by knocte** [comment]
@Jakar510 does this problem happen in v.2.4.1?

**Comment by olezhko** [comment]
> 
> 
> Deleting the obj and bin folders fixed it. Don't know if it's a visual studio issue or not.

It help me!
